# Generated by Django 4.1 on 2022-10-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_addtocart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCart',
        ),
    ]
