# Generated by Django 4.1 on 2022-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameReg', models.CharField(max_length=10)),
                ('emailReg', models.EmailField(max_length=50)),
            ],
        ),
    ]
